trigger:
  - main  # Ensure the branch name is correct (main or master)

pool:
  name: self-hosted-pool  # Specify the self-hosted pool

steps:
  - checkout: self  # Checkout the GitHub repository

  - script: |
      git clone https://pbs_student7:r2m6cldodvlk5oxdekgr7t5duzgd4wp3yzhnyspjl3xacdtfhwfa@dev.azure.com/pbsstudent7/TMR/_git/TMR  # Clone the Azure DevOps repo with credentials
      cd TMR  # Navigate into the cloned directory
      git push origin main  # Push changes to Azure DevOps
    displayName: 'Clone and Sync Changes to Azure DevOps'
