trigger:
  - main

pool:
  name: self-hosted-pool

steps:
  - checkout: self

  - script: |
      cd C:\Users\stden\OneDrive\Desktop\prototype\Kubernetes\Minikube\t t i meal reviewer minikube\tmr_api\app
      git remote set-url origin https://pbsstudent7@dev.azure.com/pbsstudent7/TMR/_git/TMR
      git push origin main
    displayName: 'Clone and Sync Changes to Azure DevOps'
