name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub (**Securely Store Credentials**)**
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Replace with your username secret
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  # Replace with your password secret

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag tmr-api-ci-cd:v1

      - name: Push the image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/tmr-api-ci-cd:v1

