name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image with a unique tag
        run: |
          IMAGE_TAG=tmr-api-ci-cd:${{ github.sha }}
          docker build . --file Dockerfile --tag $IMAGE_TAG

      - name: Push the image to Docker Hub
        run: |
          IMAGE_TAG=tmr-api-ci-cd:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/$IMAGE_TAG

