# name: Docker CI with Kubernetes Rollout on GitHub Runners

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build and push the Docker image with a unique tag
#         run: |
#           IMAGE_TAG="xalien073/tmr_api:${{ github.sha }}"
#           echo "Building image with tag: $IMAGE_TAG"
#           docker build . --file Dockerfile --tag $IMAGE_TAG
#           docker images
#           echo "Pushing image with tag: $IMAGE_TAG"
#           docker push $IMAGE_TAG

#       - name: Update `values.yaml` with new image tag
#         run: |
#           cd k8s/AKS/helm/fastapi-app
#           echo "Updating tag in values.yaml"
#           sed -i 's/tag:.*/tag: ${{ github.sha }}/' values.yaml

#       - name: Commit and push updated values.yaml
#         run: |
#           git config user.name "GitHub Actions"
#           git config user.email "actions@github.com"
#           git add values.yaml
#           git commit -m "Update image tag to ${{ github.sha }}"
#           git push https://${{ secrets.GH_TOKEN }}@github.com/xalien073/tmr_api.git main

#       - name: Deploy to Azure Kubernetes Cluster
#         run: |
#           az aks get-credentials --resource-group poona_student --name tmr-aks
#           if ! kubectl get namespace tmr; then
#             kubectl create namespace tmr
#           fi
#           helm install fastapi-app ./fastapi-app --namespace tmr
