# name: Docker CI with Kubernetes Rollout

# on:
#   push:
#     branches: ["main"]
#   pull_request:
#     branches: ["main"]

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build the Docker image with a unique tag, Push the image to Docker Hub & Update fast_deployment.yaml
#         run: |
#           IMAGE_TAG="xalien073/tmr_api:${{ github.sha }}"
#           echo "Building image with tag: $IMAGE_TAG"
#           docker build . --file Dockerfile --tag $IMAGE_TAG
#           docker images
#           echo "Pushing image with tag: $IMAGE_TAG"
#           docker push $IMAGE_TAG

#           # Clone the Kubernetes repo
#           git clone https://github.com/xalien073/tmr_api-k8s.git
#           cd tmr_api-k8s

#           # Update the image tag in fast_deployment.yaml
#           sed -i "s|image:.*|image: $IMAGE_TAG|" fast_deployment.yaml

#       - name: Commit and push updated fast_deployment.yaml
#         run: |
#           git config user.name "GitHub Actions"
#           git config user.email "actions@github.com"
#           git add fast_deployment.yaml
#           git commit -m "Update image tag to ${{ github.sha }}"
#           git push https://${{ secrets.GH_TOKEN }}@github.com/xalien073/tmr_api-k8s.git main

#       - name: Apply the new deployment to Azure Kubernetes Cluster
#         run: |
#           az aks get-credentials --resource-group <RESOURCE_GROUP> --name <CLUSTER_NAME>
#           kubectl apply -f fast_deployment.yaml
