name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: self-hosted
    # runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          timeout: '600'

      - name: Build the Docker image with a unique tag & Push the image to Docker Hub
        run: |
          $env:IMAGE_TAG="xalien073/tmr_api:${{ github.sha }}"
          Write-Host "Building image with tag: $env:IMAGE_TAG"
          docker build . --file Dockerfile --tag $env:IMAGE_TAG
          docker images
          Write-Host "Pushing image with tag: $env:IMAGE_TAG"
          docker push $env:IMAGE_TAG
        shell: powershell

      - name: Update fast_deployment.yaml with the new image tag using PowerShell
        run: |
          cd C:\Users\stden\OneDrive\Desktop\prototype\Kubernetes\tmr_api-k8s
          Write-Host "Changed directory to tmr_api-k8s"
          $image_tag="xalien073/tmr_api:${{ github.sha }}"
          (Get-Content fast_deployment.yaml) -replace 'image:.*', "image: $env:IMAGE_TAG" | Set-Content fast_deployment.yaml
        shell: powershell

      - name: Commit and push updated fast_deployment.yaml to tmr_api-k8s
        run: |
          cd C:\Users\stden\OneDrive\Desktop\prototype\Kubernetes\tmr_api-k8s
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add fast_deployment.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push https://${{ secrets.GH_TOKEN }}@github.com/xalien073/tmr_api-k8s.git main
        shell: powershell

      - name: Apply the new deployment to Minikube
        run: |
          cd C:\Users\stden\OneDrive\Desktop\prototype\Kubernetes\tmr_api-k8s
          kubectl apply -f fast_deployment.yaml
        shell: powershell


# name: Docker Image CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build-and-push:
#     runs-on: self-hosted
#     # runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#           timeout: '600'
      
#       - name: Build the Docker image with a unique tag & Push the image to Docker Hub
#         run: |
#             IMAGE_TAG="xalien073/tmr_api:${{ github.sha }}"
#             echo "Building image with tag: $IMAGE_TAG"
#             docker build . --file Dockerfile --tag $IMAGE_TAG
#             docker images
#             echo "Pushing image with tag: $IMAGE_TAG"
#             docker push $IMAGE_TAG
      
#     #   - name: Build the Docker image with a unique tag & Push the image to Docker Hub
#     #     run: |
#     #         set IMAGE_TAG=xalien073/tmr_api:${{ github.sha }}
#     #         echo Building image with tag: %IMAGE_TAG%
#     #         docker build . --file Dockerfile --tag %IMAGE_TAG%
#     #         docker images
#     #         echo Pushing image with tag: %IMAGE_TAG%
#     #         docker push %IMAGE_TAG%
#     #     shell: cmd

#       - name: Update fast_deployment.yaml with the new image tag using PowerShell
#         run: |
#           cd C:\Users\stden\OneDrive\Desktop\prototype\Kubernetes\tmr_api-k8s
#           echo Changed directory to tmr_api-k8s
#           $image_tag="xalien073/tmr_api:${{ github.sha }}"
#           (Get-Content fast_deployment.yaml) -replace 'image:.*', "image: $image_tag" | Set-Content fast_deployment.yaml
      
#       - name: Commit and push updated fast_deployment.yaml to tmr_api-k8s
#         run: |
#           cd C:\Users\stden\OneDrive\Desktop\prototype\Kubernetes\tmr_api-k8s
#           git config user.name "GitHub Actions"
#           git config user.email "actions@github.com"
#           git add fast_deployment.yaml
#           git commit -m "Update image tag to ${{ github.sha }}"
#           git push https://${{ secrets.GH_TOKEN }}@github.com/xalien073/tmr_api-k8s.git main
      
#       - name: Apply the new deployment to Minikube
#         run: |
#           cd C:\Users\stden\OneDrive\Desktop\prototype\Kubernetes\tmr_api-k8s
#           kubectl apply -f fast_deployment.yaml

